import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/project.dart';
import '../services/api_client.dart';
import '../services/device_bridge.dart';
import '../services/geofence_bridge.dart';
import 'login_screen.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> with WidgetsBindingObserver {
  Map<String, dynamic>? data; DevicePermissionStatus? permissions; String? error; bool loading = true;
  @override void initState() { super.initState(); WidgetsBinding.instance.addObserver(this); load(); }
  @override void dispose() { WidgetsBinding.instance.removeObserver(this); super.dispose(); }
  @override void didChangeAppLifecycleState(AppLifecycleState state) { if (state == AppLifecycleState.resumed) refreshPermissions(register: true); }
  Future<void> refreshPermissions({bool register = false}) async { try { final s = await DeviceBridge().status(); if (mounted) setState(() => permissions = s); if (register && s.ready && data != null) await registerGeofences(); } catch (_) {} }
  Future<void> registerGeofences() async { if (data == null || permissions?.ready != true) return; final projects = (data!['projects'] as List? ?? const []).map((x) => ProjectGeofence.fromJson(Map<String, dynamic>.from(x as Map))).toList(); final p = await SharedPreferences.getInstance(); final token = p.getString('token'); final device = p.getString('device_uuid'); if (token == null || device == null) return; await GeofenceBridge().register(projects: projects, bearerToken: token, deviceUuid: device); }
  Future<void> load() async { if (mounted) setState(() { loading = true; error = null; }); try { permissions = await DeviceBridge().status(); data = await ApiClient().getJson('/bootstrap'); if (permissions?.ready == true) await registerGeofences(); } catch (e) { error = e.toString().replaceFirst('Exception: ', ''); } finally { if (mounted) setState(() => loading = false); } }
  Future<void> signOut() async { await GeofenceBridge().clear(); final p = await SharedPreferences.getInstance(); await p.remove('token'); if (mounted) Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (_) => const LoginScreen()), (_) => false); }
  Widget statusRow(String label, bool ok, {String? action, VoidCallback? onTap}) => ListTile(contentPadding: EdgeInsets.zero, leading: Icon(ok ? Icons.check_circle : Icons.warning_amber_rounded), title: Text(label), trailing: !ok && action != null ? TextButton(onPressed: onTap, child: Text(action)) : null);
  @override Widget build(BuildContext context) { final open = (data?['open_sessions'] as List?) ?? const []; final projectCount = (data?['projects'] as List?)?.length ?? 0; final p = permissions; return Scaffold(appBar: AppBar(title: const Text('Site Attendance'), actions: [IconButton(onPressed: signOut, icon: const Icon(Icons.logout))]), body: RefreshIndicator(onRefresh: load, child: ListView(physics: const AlwaysScrollableScrollPhysics(), padding: const EdgeInsets.all(18), children: [if (loading) const LinearProgressIndicator(), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(open.isEmpty ? 'Not checked in' : 'Checked in', style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 8), Text(open.isEmpty ? 'Automatic check-in will occur when you enter an assigned site.' : '${open.first['project']['project_code']} · ${open.first['project']['name']}', style: Theme.of(context).textTheme.headlineSmall), const SizedBox(height: 8), Text('$projectCount assigned sites loaded')]))), const SizedBox(height: 16), Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Background attendance setup', style: Theme.of(context).textTheme.titleMedium), statusRow('Precise location', p?.fineLocation == true, action: 'Allow', onTap: () async { await DeviceBridge().requestFineLocation(); await refreshPermissions(register: true); }), statusRow('Allow location all the time', p?.backgroundLocation == true, action: 'Settings', onTap: () => DeviceBridge().openAppSettings()), statusRow('Location services', p?.locationServices == true, action: 'Turn on', onTap: () => DeviceBridge().openLocationSettings()), statusRow('Notifications', p?.notifications == true, action: 'Allow', onTap: () async { await DeviceBridge().requestNotifications(); await refreshPermissions(); })]))), if (error != null) Padding(padding: const EdgeInsets.only(top: 16), child: Text(error!, style: const TextStyle(color: Colors.red)))]))); }
}
